GET http://localhost:8001/products

###
GET http://localhost:8001/product/1

###
POST http://localhost:8001/product HTTP/1.1
content-type: application/json

{
    "name": "Churrasquinho",
    "price": 5.50
}


###
POST http://172.104.9.40:8001/product HTTP/1.1
content-type: application/json

{
    "name": "mamao",
    "price": 5.778
}
